### ISSUE TITLE
start.sh: no such file or directory

### ISSUE THREAD

**Issue by bertt** [geosolutions-it/digital-twin-toolbox#23]
Hi, I'm trying to follow the setup wiki (https://github.com/geosolutions-it/digital-twin-toolbox/wiki/Setup-and-usage) but get an error after 'docker compose up', and the web app doesn't start

```
digital_twin_toolbox          | exec /usr/src/app/start.sh: no such file or directory
digital_twin_toolbox exited with code 1
```

**Comment by bertt** [comment]
something with line endings on windows, got it working after doing '$ git config --global core.autocrlf false'

**Comment by allyoucanmap** [comment]
@bertt thanks for trying this project and for you work on pg2b3dm and i3dm.export, we tried mainly with linux ubuntu and with WSL on windows, I have just updated the [wiki](https://github.com/geosolutions-it/digital-twin-toolbox/wiki/Setup-and-usage) with the following

![image](https://github.com/geosolutions-it/digital-twin-toolbox/assets/19175505/5fb193fb-06d9-4a53-b983-4a882827072c)

this should solve the problem on the initial clone also on Windows OS, thanks again
