### ISSUE TITLE
Digital Twin CI/CD workflow

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/digital-twin-toolbox#33]
Implement deployment actions/jobs

- Jenkins CI/CD is necessary to build the project and publish artifacts on geosolutions dockerhub (see the wiki for build and deployment instructions)
- Proper github action should be provided to built the project and run unit test for each coming PR/commit

**Comment by randomorder** [comment]
@allyoucanmap can you please link or add instructions on how to manually build the artifcat ?

**Comment by allyoucanmap** [comment]
@randomorder The two artifact that we need to build are frontend and backend images:

[frontend](https://github.com/geosolutions-it/digital-twin-toolbox/blob/main/docker-compose.yml#L146)
```
docker compose -f docker-compose.yml build frontend
```

[backend](https://github.com/geosolutions-it/digital-twin-toolbox/blob/main/docker-compose.yml#L41)
```
docker compose -f docker-compose.yml build backend
```

Here we included [deployment](https://github.com/geosolutions-it/digital-twin-toolbox/wiki/Deployment) instructions.
The project has been created on top of this [template](https://github.com/fastapi/full-stack-fastapi-template) so we could take a look also to the github actions for [staging](https://github.com/fastapi/full-stack-fastapi-template/blob/master/.github/workflows/deploy-staging.yml) and [production](https://github.com/fastapi/full-stack-fastapi-template/blob/master/.github/workflows/deploy-production.yml)

Env file [here](https://github.com/geosolutions-it/digital-twin-toolbox/blob/main/.env)

**Comment by randomorder** [comment]
@tdipisa 
For the time @allyoucanmap manually published the docker images on the docker hub. They are available [here](docker pull geosolutionsit/digital-twin-toolbox-backend) and [here](docker pull geosolutionsit/digital-twin-toolbox-frontend).

**Comment by tdipisa** [comment]
> So, `build -> test -> deploy` the two images on every commit on `main` branch. and `build -> test` for every PR to `main` branch.
> 
> @randomorder Sure, I'll set this up. I estimate about 3 hours.

That's sounds good to me (FYI @allyoucanmap).

**Comment by randomorder** [comment]
@mo3rfan please check the comments in the PR.
